export const PROOF_COPY = {
  ko: {
    header: {
      headline: '우리 시그널이 실제로 어떻게 작동했나',
      subtitle: '모든 사이클은 오픈/청산 시점이 기록되며, 손실 사이클도 그대로 포함됩니다',
      generatedSuffix: 'KST 기준 · signal_cycles 전수 집계',
      noData: '데이터 없음',
      failed: '조회 실패',
      accumulating: '데이터 축적 중',
    },
    sections: {
      simulator: { title: '투자 수익 시뮬레이터', sub: '' },
      symbol: { title: '시그널 종목별 통계', sub: '' },
    },
    filters: {
      streams: '스트림',
      category: '구분',
      pulse: 'Pulse',
      wave: 'Wave',
      trend: '추세',
      nonTrend: '비추세',
      reversal: '역추세',
      signal: '신호',
      allSymbols: '전체종목',
      symbol: '종목',
    },
    quality: {
      winRate: '승률',
      riskReward: '손익비',
      last30d: '30일',
      all: '전체',
    },
    simulator: {
      step2Title: '통계 기준별 예상 수익',
      basisRecent30: '최근 30일 통계',
      basisTotal: '총 누적 통계',
      basisTag: '기준',
      seed: '시드머니',
      entryRatio: '진입 비율',
      entryRatioHelp: '총자산 중 한 포지션에 쓸 비율입니다.',
      leverage: '레버리지',
      settingsButton: '수익 시뮬레이션',
      settingsTitle: '수익 시뮬레이션 기준',
      criteriaValue: (seed: string, entryRatio: number, leverage: number) =>
        `$${seed} · ${entryRatio}% · ${leverage}x`,
      annualTitle: '1년 후 총자산 비교',
      annualSub: (fee: string) => `이용료 ${fee} 차감 후`,
      annualUnavailable: '연산에 필요한 기간 데이터가 부족합니다',
      showAll: '전체보기',
      showLess: '간략히',
    },
    scenarios: {
      standard: {
        title: '일반 진입 기준',
        badge: '일반',
        returnLabel: '계좌수익률',
        profitLabel: '계좌수익금',
      },
      discounted: {
        title: '할인적용 진입 기준',
        badge: '할인적용',
        returnLabel: '계좌수익률',
        profitLabel: '계좌수익금',
      },
    },
    metric: {
      winRate: '승률',
      recommended: '추천',
      maxProfit: '최고 수익',
      maxLoss: '최대 손실',
      recovery: '이용료 회수(예상)',
    },
    table: {
      category: '구분',
      standard: '일반',
      discounted: '할인적용',
      asset: '자산',
      recent30: '최근 30일',
      recent3mo: '최근 3개월',
      cumulative: '누적',
      entries: '진입횟수',
      pnlUsd: '손익금',
      pnlPct: '손익률',
      accountReturn: '계좌수익률',
      accountProfit: '계좌수익금',
      maxProfit: '최고 수익',
      maxProfitPct: '최고 수익률',
      maxLoss: '최대 손실',
      maxLossPct: '최대 손실률',
      avgWinRate: '평균승률',
      avgRatio: '평균손익비',
      accountRatio: '계좌손익비',
      avgHoldTime: '평균보유시간',
      recovery: '이용료 회수(예상)',
      empty: '표시할 closed Pulse cycle이 없습니다',
    },
    time: { minute: '분', hour: '시간', day: '일', about: '약 ', month: '개월' },
    footer: '모든 사이클은 signal_cycles 청산 기록 기준 · 엔진 PULSE(1분 봉) · WAVE(10분 봉)',
  },
  en: {
    header: {
      headline: 'How our signals performed in real closed cycles',
      subtitle: 'Every cycle includes its open and close, including losing trades.',
      generatedSuffix: 'KST · full signal_cycles aggregate',
      noData: 'No data',
      failed: 'Load failed',
      accumulating: 'Collecting data',
    },
    sections: {
      simulator: { title: 'Investment Return Simulator', sub: '' },
      symbol: { title: 'Signal Stats by Symbol', sub: '' },
    },
    filters: {
      streams: 'Stream',
      category: 'Category',
      pulse: 'Pulse',
      wave: 'Wave',
      trend: 'Trend',
      nonTrend: 'Non-trend',
      reversal: 'Reversal',
      signal: 'Signal',
      allSymbols: 'All Symbols',
      symbol: 'Symbol',
    },
    quality: {
      winRate: 'Win Rate',
      riskReward: 'Risk/Reward',
      last30d: '30d',
      all: 'All',
    },
    simulator: {
      step2Title: 'Expected Return by Basis',
      basisRecent30: 'Last 30 Days Basis',
      basisTotal: 'Total Cumulative Basis',
      basisTag: 'Basis',
      seed: 'Seed Money',
      entryRatio: 'Entry Ratio',
      entryRatioHelp: 'Percent of total capital used for one position.',
      leverage: 'Leverage',
      settingsButton: 'Profit Simulation',
      settingsTitle: 'Profit Simulation Basis',
      criteriaValue: (seed: string, entryRatio: number, leverage: number) =>
        `$${seed} · ${entryRatio}% · ${leverage}x`,
      annualTitle: 'Total Asset After 1 Year',
      annualSub: (fee: string) => `After ${fee} subscription fee`,
      annualUnavailable: 'Not enough elapsed-time data to project this basis',
      showAll: 'Show all',
      showLess: 'Show less',
    },
    scenarios: {
      standard: {
        title: 'Standard Entry Basis',
        badge: 'Standard',
        returnLabel: 'Return estimate',
        profitLabel: 'Expected profit',
      },
      discounted: {
        title: 'Discounted Entry Basis',
        badge: 'Discounted',
        returnLabel: 'Return estimate',
        profitLabel: 'Expected profit',
      },
    },
    metric: {
      winRate: 'Win Rate',
      recommended: 'Recommended',
      maxProfit: 'Highest Profit',
      maxLoss: 'Highest Loss',
      recovery: 'Fee Recovery Estimate',
    },
    table: {
      category: 'Category',
      standard: 'Standard',
      discounted: 'Discounted',
      asset: 'Asset',
      recent30: 'Last 30 Days',
      recent3mo: 'Last 3 Months',
      cumulative: 'Cumulative',
      entries: 'Entries',
      pnlUsd: 'P&L',
      pnlPct: 'Return',
      accountReturn: 'Account Return',
      accountProfit: 'Account Profit',
      maxProfit: 'Highest Profit',
      maxProfitPct: 'Highest Profit %',
      maxLoss: 'Highest Loss',
      maxLossPct: 'Highest Loss %',
      avgWinRate: 'Avg Win Rate',
      avgRatio: 'Avg P/L Ratio',
      accountRatio: 'Account P/L Ratio',
      avgHoldTime: 'Avg Hold Time',
      recovery: 'Fee Recovery Est.',
      empty: 'No closed Pulse cycles to display',
    },
    time: { minute: 'm', hour: 'h', day: 'd', about: 'about ', month: 'mo' },
    footer: 'All cycles are based on closed signal_cycles records · PULSE 1m · WAVE 10m',
  },
  ja: {
    header: {
      headline: 'シグナルの実績をクローズ済みサイクルで確認',
      subtitle: 'すべてのサイクルはエントリーと決済を記録し、損失サイクルも含めています。',
      generatedSuffix: 'KST 基準 · signal_cycles 全件集計',
      noData: 'データなし',
      failed: '取得失敗',
      accumulating: 'データ集計中',
    },
    sections: {
      simulator: { title: '投資収益シミュレーター', sub: '' },
      symbol: { title: '銘柄別統計', sub: '' },
    },
    filters: {
      streams: 'ストリーム',
      category: '区分',
      pulse: 'Pulse',
      wave: 'Wave',
      trend: 'Trend',
      nonTrend: 'Non-trend',
      reversal: 'Reversal',
      signal: 'シグナル',
      allSymbols: '全銘柄',
      symbol: '銘柄',
    },
    quality: {
      winRate: '勝率',
      riskReward: '損益比',
      last30d: '30日',
      all: '全体',
    },
    simulator: {
      step2Title: '基準別想定収益',
      basisRecent30: '直近30日基準',
      basisTotal: '累積基準',
      basisTag: '基準',
      seed: 'シード資金',
      entryRatio: 'Entry Ratio',
      entryRatioHelp: 'Percent of total capital used for one position.',
      leverage: 'レバレッジ',
      settingsButton: '収益シミュレーション',
      settingsTitle: '収益シミュレーション基準',
      criteriaValue: (seed: string, entryRatio: number, leverage: number) =>
        `$${seed} · ${entryRatio}% · ${leverage}x`,
      annualTitle: '1年後の総資産比較',
      annualSub: (fee: string) => `利用料 ${fee} 差し引き後`,
      annualUnavailable: '計算に必要な期間データが不足しています',
      showAll: 'すべて表示',
      showLess: '簡略表示',
    },
    scenarios: {
      standard: {
        title: '通常エントリー基準',
        badge: 'Standard',
        returnLabel: '基準収益率',
        profitLabel: '想定利益',
      },
      discounted: {
        title: '割引適用エントリー基準',
        badge: 'Discounted',
        returnLabel: '基準収益率',
        profitLabel: '想定利益',
      },
    },
    metric: {
      winRate: '勝率',
      recommended: '推奨',
      maxProfit: '最高収益',
      maxLoss: '最大損失',
      recovery: '利用料回収まで(予想)',
    },
    table: {
      category: '区分',
      standard: '通常',
      discounted: '割引適用',
      asset: '銘柄',
      recent30: '直近30日',
      recent3mo: '直近3か月',
      cumulative: '累積',
      entries: '回数',
      pnlUsd: '損益',
      pnlPct: '収益率',
      accountReturn: '口座収益率',
      accountProfit: '口座収益額',
      maxProfit: '最高収益',
      maxProfitPct: '最高収益率',
      maxLoss: '最大損失',
      maxLossPct: '最大損失率',
      avgWinRate: '平均勝率',
      avgRatio: '平均損益比',
      accountRatio: '口座損益比',
      avgHoldTime: '平均保有時間',
      recovery: '利用料回収(予想)',
      empty: '表示できるクローズ済み Pulse サイクルがありません',
    },
    time: { minute: '分', hour: '時間', day: '日', about: '約', month: 'か月' },
    footer: 'すべてのサイクルは signal_cycles の決済記録基準 · PULSE(1分足) · WAVE(10分足)',
  },
} as const;

export type ProofLanguage = keyof typeof PROOF_COPY;
export type ProofCopy = (typeof PROOF_COPY)[ProofLanguage];
