export const COLUMN_LABELS: Record<string, string> = {
  symbol: '종목',
  direction: '방향',
  entryPrice: '진입가',
  currentPrice: '현재가',
  pnlPercent: '손익률',
  pnl: '손익',
  pnlAmount: '손익액',
  extraSignal: '추가신호',
  remainingTime: '남은시간',
  discountPrice: '할인가',
  discountRate: '할인적용율',
  additionalEntryPrice: '추가진입가',
  additionalDiscountAmount: '추가할인금액',
  discountGainPercent: '할인진입(%)',
  discountGainAmount: '할인진입($)',
  partialClosePrice: '부분청산가',
  lockedProfitAmount: '확정수익금',
  lockedProfitPercent: '확정수익률',
  lockedAmount: '확정수익액',
  lockedPercent: '확정수익율',
  shortTrend: '단기추세',
  longTrend: '장기추세',
  nontrendDuration: '비추세지속(분)',
  volatility: '변동성',
  pnl1dAmount: '1일손익금',
  pnl1dPercent: '1일손익률',
  pnl7dAmount: '7일손익금',
  pnl7dPercent: '7일손익률',
  lastCloseTime: '최근청산시각',
  todaySignalCount: '오늘신호수',
  avgCycleTime: '평균사이클(분)',
  closePrice: '청산가',
  investPnlAmount: '투자손익금',
  investPnlPercent: '투자손익률',
  cycleTime: '사이클(분)',
  section: '섹션',
  status: '상태',
  holdDuration: '보유시간',
  enteredAt: '진입시간',
  averageEntryPrice: '진입평단가',
  avgPnlAmount: '평단수익액',
  avgPnlPercent: '평단수익율',
  elapsedSeconds: '진입 시간',
  nonTrendEntryTime: '추세변경시간',
  partialSignal: '추가신호',
  partialExitPrice: '분할청산가',
  partialExitTime: '추가진입시간',
  nonTrendType: '비추세 구분',
  additionalSignal: '추가신호',
  additionalEntryTime: '추가진입시간',
  dailyWinRate: '1일-7일 승률',
  weeklyWinRate: '7일-30일 승률',
  lastEntryPrice: '최근 진입가',
  lastExitPrice: '최근 청산가',
  lastPnlAmount: '최근 수익($)',
  lastPnlPercent: '최근 수익(%)',
};
