import { FAIcon, type FAIconProps } from './FAIcon';

export type IconProps = Omit<FAIconProps, 'icon'>;

// Lucide-named components that render FAIcon
export const X = (props: IconProps) => <FAIcon icon="xmark" {...props} />;
export const ChevronDown = (props: IconProps) => <FAIcon icon="chevron-down" {...props} />;
export const ChevronUp = (props: IconProps) => <FAIcon icon="chevron-up" {...props} />;
export const ChevronLeft = (props: IconProps) => <FAIcon icon="chevron-left" {...props} />;
export const ChevronRight = (props: IconProps) => <FAIcon icon="chevron-right" {...props} />;
export const ArrowLeft = (props: IconProps) => <FAIcon icon="arrow-left" {...props} />;
export const ArrowRight = (props: IconProps) => <FAIcon icon="arrow-right" {...props} />;
export const TrendingUp = (props: IconProps) => <FAIcon icon="arrow-trend-up" {...props} />;
export const TrendingDown = (props: IconProps) => <FAIcon icon="arrow-trend-down" {...props} />;
export const Code = (props: IconProps) => <FAIcon icon="code" {...props} />;
export const Bell = (props: IconProps) => <FAIcon icon="bell" {...props} />;
export const RotateCcw = (props: IconProps) => <FAIcon icon="rotate-left" {...props} />;
export const RefreshCw = (props: IconProps) => <FAIcon icon="arrows-rotate" {...props} />;
export const Copy = (props: IconProps) => <FAIcon icon="copy" {...props} />;
export const Minus = (props: IconProps) => <FAIcon icon="minus" {...props} />;
export const Plus = (props: IconProps) => <FAIcon icon="plus" {...props} />;
export const Eye = (props: IconProps) => <FAIcon icon="eye" {...props} />;
export const Calendar = (props: IconProps) => <FAIcon icon="calendar" {...props} />;
export const AlertTriangle = (props: IconProps) => <FAIcon icon="triangle-exclamation" {...props} />;
export const AlertCircle = (props: IconProps) => <FAIcon icon="circle-exclamation" {...props} />;
export const CheckCircle = (props: IconProps) => <FAIcon icon="circle-check" {...props} />;
export const Check = (props: IconProps) => <FAIcon icon="check" {...props} />;
export const Shield = (props: IconProps) => <FAIcon icon="shield" {...props} />;
export const Zap = (props: IconProps) => <FAIcon icon="bolt" {...props} />;
export const Info = (props: IconProps) => <FAIcon icon="circle-info" {...props} />;
export const Flame = (props: IconProps) => <FAIcon icon="fire" {...props} />;
export const MoreHorizontal = (props: IconProps) => <FAIcon icon="ellipsis" {...props} />;
export const Loader2 = (props: IconProps) => <FAIcon icon="spinner" spin {...props} />;
export const Send = (props: IconProps) => <FAIcon icon="paper-plane" {...props} />;
export const Lock = (props: IconProps) => <FAIcon icon="lock" {...props} />;
export const Clock = (props: IconProps) => <FAIcon icon="clock" {...props} />;
export const Activity = (props: IconProps) => <FAIcon icon="chart-line" {...props} />;
export const Sparkles = (props: IconProps) => <FAIcon icon="sparkles" {...props} />;
export const Trash = (props: IconProps) => <FAIcon icon="trash" {...props} />;
export const Edit = (props: IconProps) => <FAIcon icon="pen" {...props} />;
export const Settings = (props: IconProps) => <FAIcon icon="gear" {...props} />;
export const User = (props: IconProps) => <FAIcon icon="user" {...props} />;
export const LogOut = (props: IconProps) => <FAIcon icon="right-from-bracket" {...props} />;
export const Search = (props: IconProps) => <FAIcon icon="magnifying-glass" {...props} />;
export const Filter = (props: IconProps) => <FAIcon icon="filter" {...props} />;
export const Download = (props: IconProps) => <FAIcon icon="download" {...props} />;
export const Upload = (props: IconProps) => <FAIcon icon="upload" {...props} />;
export const Save = (props: IconProps) => <FAIcon icon="floppy-disk" {...props} />;
export const Star = (props: IconProps) => <FAIcon icon="star" {...props} />;
export const Heart = (props: IconProps) => <FAIcon icon="heart" {...props} />;
export const Share = (props: IconProps) => <FAIcon icon="share" {...props} />;
export const ExternalLink = (props: IconProps) => <FAIcon icon="arrow-up-right-from-square" {...props} />;
export const Play = (props: IconProps) => <FAIcon icon="play" {...props} />;
export const Pause = (props: IconProps) => <FAIcon icon="pause" {...props} />;
export const SkipBack = (props: IconProps) => <FAIcon icon="backward-step" {...props} />;
export const SkipForward = (props: IconProps) => <FAIcon icon="forward-step" {...props} />;
export const Circle = (props: IconProps) => <FAIcon icon="circle" {...props} />;
export const Wifi = (props: IconProps) => <FAIcon icon="wifi" {...props} />;
export const WifiOff = (props: IconProps) => <FAIcon icon="wifi" {...props} />;
